### ISSUE TITLE
Wechaty 社区 “暑期2020” 各个项目确认表

### ISSUE THREAD

**Issue by rickyyin98** [wechaty/summer-of-code#16]
Wechaty 社区将为每一个项目在此 issue 下面开放一个评论，由社区导师负责编辑，其中包括：选择哪位同学作为项目参与者、是否逐步推进相关事项等信息，当全部信息填写完成后，在此处为对应项目打✅。

### 多平台（Muti-Plat）
- [ ] （难度：高）基于开放 API 封装 Wechaty 接口下的企业微信聊天机器人 #2 
- [ ] （难度：高）基于开放 API 封装 Wechaty 接口下的钉钉聊天机器人 #11 
- [ ] （难度：高）基于开放 API 封装 Wechaty 接口下的飞书聊天机器人 #12 
- [ ] （难度：高）基于 RPA 封装 Wechaty 接口下的抖音聊天机器人 #13 
- [ ] （难度：高）基于 RPA 封装 Wechaty 接口下的快手聊天机器人 #14 

### 多语言（Muti-Lang）
- [ ] （难度：低）Wechaty Java 移植组件开发 #4 
- [ ] （难度：中）Go-wechaty Github Action optimization #8 
- [ ] （难度：中）为 go-wechaty 设计实现 插件体系 #9 

### 多功能（Plugin）
- [ ] （难度：中）基于python-wechaty的群聊助手机器人 #6 
- [ ] （难度：中）基于Python-wechaty建立一个斗图机器人 #7   
- [ ] （难度：低）编写一个“每日一句”插件 #10  

### 项目信息模板
- [ ]  项目名称：XXXX
- [ ]  项目导师：XXXX（邮箱：XXXX）；XXXX（邮箱：XXXX）
- [ ]  项目总报名人数：X
- [ ]  项目确定入选人：XXXX（邮箱：XXXX；学校：XXXX）
- [ ]  添加入选人并开始进行相关工作

**Comment by rickyyin98** [comment]
- [ ]  项目名称：基于开放 API 封装 Wechaty 接口下的企业微信聊天机器人
- [ ]  项目导师：高原（gaoyuan@juzi.bot）；李佳芮（rui@juzi.bot）
- [ ]  项目总报名人数：2
- [ ]  项目确定入选人：XXXX（邮箱：XXXX；学校：XXXX）
- [ ]  添加入选人并开始进行相关工作

**Comment by rickyyin98** [comment]
- [ ]  项目名称：基于开放 API 封装 Wechaty 接口下的钉钉聊天机器人
- [ ]  项目导师：高原（gaoyuan@juzi.bot）；李佳芮（rui@juzi.bot）
- [ ]  项目总报名人数：2
- [ ]  项目确定入选人：XXXX（邮箱：XXXX；学校：XXXX）
- [ ]  添加入选人并开始进行相关工作

**Comment by rickyyin98** [comment]
- [ ]  项目名称：基于开放 API 封装 Wechaty 接口下的飞书聊天机器人
- [ ]  项目导师：高原（gaoyuan@juzi.bot）；李佳芮（rui@juzi.bot）
- [ ]  项目总报名人数：1
- [ ]  项目确定入选人：XXXX（邮箱：XXXX；学校：XXXX）
- [ ]  添加入选人并开始进行相关工作

**Comment by rickyyin98** [comment]
- [x]  项目名称：基于 RPA 封装 Wechaty 接口下的抖音聊天机器人
- [x]  项目导师：尹伯昊（yinbohao@juzi.bot）；王凯峰
- [x]  项目总报名人数：1
- [ ]  项目确定入选人：XXXX（邮箱：XXXX；学校：XXXX）
- [ ]  添加入选人并开始进行相关工作

**Comment by rickyyin98** [comment]
- [x]  项目名称：基于 RPA 封装 Wechaty 接口下的快手聊天机器人
- [x]  项目导师：尹伯昊（yinbohao@juzi.bot）；王凯峰
- [x]  项目总报名人数：1
- [ ]  项目确定入选人：XXXX（邮箱：XXXX；学校：XXXX）
- [ ]  添加入选人并开始进行相关工作

**Comment by rickyyin98** [comment]
- [x]  项目名称：Wechaty Java 移植组件开发
- [x]  项目导师：刁政欣（diaozxin@gmail.com）
- [x]  项目总报名人数：2
- [ ]  项目确定入选人：XXXX（邮箱：XXXX；学校：XXXX）
- [ ]  添加入选人并开始进行相关工作

**Comment by rickyyin98** [comment]
- [x]  项目名称：Go-wechaty Github Action optimization
- [x]  项目导师：丁小雨（614422099@qq.com）；丁超飞（dchaofei@163.com）；李博杰（silkage@silkage.net）
- [x]  项目总报名人数：1
- [ ]  项目确定入选人：XXXX（邮箱：XXXX；学校：XXXX）
- [ ]  添加入选人并开始进行相关工作

**Comment by rickyyin98** [comment]
- [x]  项目名称：为 go-wechaty 设计实现 插件体系
- [x]  项目导师：丁小雨（614422099@qq.com）；丁超飞（dchaofei@163.com）；李博杰（silkage@silkage.net）
- [x]  项目总报名人数：2
- [ ]  项目确定入选人：XXXX（邮箱：XXXX；学校：XXXX）
- [ ]  添加入选人并开始进行相关工作

**Comment by rickyyin98** [comment]
- [x]  项目名称：基于python-wechaty的群聊助手机器人
- [x]  项目导师：吴京京（1435130236@qq.com）
- [x]  项目总报名人数：6
- [ ]  项目确定入选人：XXXX（邮箱：XXXX；学校：XXXX）
- [ ]  添加入选人并开始进行相关工作

**Comment by rickyyin98** [comment]
- [x]  项目名称：基于Python-wechaty建立一个斗图机器人
- [x]  项目导师：黄纯洪（huangaszaq@gmail.com）
- [x]  项目总报名人数：4
- [ ]  项目确定入选人：XXXX（邮箱：XXXX；学校：XXXX）
- [ ]  添加入选人并开始进行相关工作

**Comment by rickyyin98** [comment]
- [x]  项目名称：编写一个“每日一句”插件
- [x]  项目导师：Gcaufy（gcaufy@gmail.com）
- [x]  项目总报名人数：6
- [ ]  项目确定入选人：XXXX（邮箱：XXXX；学校：XXXX）
- [ ]  添加入选人并开始进行相关工作

**Comment by huan** [comment]
Why this issue has been closed? 

We should explain the reason when we operate issues/prs, and we should also link the related issues together so that we can keep tracking everything together.

Link to #3
