### ISSUE TITLE
Wechaty 社区 “暑期2020” 项目列表

### ISSUE THREAD

**Issue by huan** [wechaty/summer-of-code#3]
### 多平台（Muti-Plat）
- [ ] （难度：高）基于开放 API 封装 Wechaty 接口下的企业微信聊天机器人 #2 
- [ ] （难度：高）基于开放 API 封装 Wechaty 接口下的钉钉聊天机器人 #11 
- [ ] （难度：高）基于开放 API 封装 Wechaty 接口下的飞书聊天机器人 #12 
- [ ] （难度：高）基于 RPA 封装 Wechaty 接口下的抖音聊天机器人 #13 
- [ ] （难度：高）基于 RPA 封装 Wechaty 接口下的快手聊天机器人 #14 

### 多语言（Muti-Lang）
- [ ] （难度：低）Wechaty Java 移植组件开发 #4 
- [ ] （难度：中）Go-wechaty Github Action optimization #8 
- [ ] （难度：中）为 go-wechaty 设计实现 插件体系 #9 

### 多功能（Plugin）
- [ ] （难度：中）基于python-wechaty的群聊助手机器人 #6 
- [ ] （难度：中）基于Python-wechaty建立一个斗图机器人 #7   
- [ ] （难度：低）编写一个“每日一句”插件 #10

**Comment by huan** [comment]
Close this issue because Summer 2020 has been finished.
